:PROPERTIES:
:header-args:conf-space: :tangle config :padline yes
:END:

* Virtual Desktop
Use just one Desktop, with a size of 3x3 pages:
#+begin_src conf-space
  DesktopSize 3x3
#+end_src

Enable changing the viewport by hitting the edges with the mouse:
#+begin_src conf-space
  EdgeScroll 100 100
  EdgeThickness 1
#+end_src

* RandR Support

** (De-)Activation of (Dis-)connected monitors
After a monitor is connected, its status can be verifed by executing:
#+begin_src shell :results verbatim :wrap example
  xrandr | grep DP
#+end_src

It should result in something like:
#+begin_example
  eDP-1 connected primary 2048x1152+0+0 (normal left inverted right x axis y axis) 344mm x 194mm
  DP-1 connected (normal left inverted right x axis y axis)
  DP-2 disconnected (normal left inverted right x axis y axis)
  DP-3 disconnected (normal left inverted right x axis y axis)
  DP-4 disconnected (normal left inverted right x axis y axis)
#+end_example

After connecting a new monitor, it has to be activated with:
#+begin_src shell :results none
  xrandr --output DP-1 --auto
#+end_src

This leads to
1. Firing /FvwmEvent/ the event /monitor_enabled/
2. Execution of /RandRFunc/

Disconnecing a monitor leads to
1. Executing of /RandRFunc/
2. Firing FvwmEvent the event /monitor_disabled/

After a monitor has been disconnected, it has to be deactivated, by executing:
#+begin_src shell :results none
  xrandr --output DP-1 --off
#+end_src

*Note*: Deactivating a monitor does not fire any /FvwmEvent/ events, as long as it is still connected. The function /RandRFunc/ and the event /monitor_disabled/ only comes into effect when the monitor has been disconnected. 

Two functions are added:
1. Activate a monitor as primary monitor:
   #+begin_src conf-space
     DestroyFunc ActivateMonitor
     AddToFunc ActivateMonitor
      + I Exec xrandr --output $0 --auto --primary
   #+end_src

   The activated monitor is set as primary monitor, so desktop resolution and /FvwmPager/ can be adjusted, by restarting FVWM.

2. Deactivate a monitor and make the standard monitor the primary monitor again:
   #+begin_src conf-space
     DestroyFunc DeactivateMonitor
     AddToFunc DeactivateMonitor
      + I Exec xrandr --output $0 --off
      + I Exec xrandr --output eDP-1 --primary
   #+end_src

Both functions are configured to (de-)activate /DP-1/, if a monitor is connected:
#+begin_src conf-space
  ,*FvwmEvent: Cmd
  ,*FvwmEvent: monitor_disabled "DeactivateMonitor DP-1"
  ,*FvwmEvent: monitor_enabled "ActivateMonitor DP-1"
#+end_src

*Note*: After FVWM has been (re)started and a monitor is connected the first time, neither /RandRFunc/ is executed nor /FvwmEvent/ events are fired. Therefore /ActivateMonitor/ has to be executed manually once. After that, the automatic (de-)activation of /DP-1/ works.

* Initialization
Set a background image on initialization:
#+begin_src conf-space
  DestroyFunc InitFunction
  AddToFunc   InitFunction
  + I Exec exec fvwm3-root \
    ${FVWM_DATADIR}/default-config/images/background/bg3.png
#+end_src

Start the modules /FvwmPager/ and /FvwmEvent/, on startups and restarts, after FVWM has read its config:
#+begin_src conf-space
  DestroyFunc StartFunction
  AddToFunc   StartFunction
  + I Module FvwmPager
  + I Module FvwmEvent
#+end_src

* Fonts
Set the default font:
#+begin_src conf-space
  DefaultFont "xft:Sans:antialias=True:size=10"
#+end_src

* Keyboard bindings

** Invoke the root menu
Invoke the [[* Root menu][root menu]] with /Super_L+F1/
#+begin_src conf-space
  Key F1 A 4  PopUp MenuFvwmRoot
#+end_src

** Enable brightness control
After installing ~brightnessctl~ and ~brightness-udev~, add these keybindings:
#+begin_src conf-space
  Key XF86MonBrightnessDown A A Exec exec brightnessctl s 10%-
  Key XF86MonBrightnessUp   A A Exec exec brightnessctl s 10%+
#+end_src

** Enable audio controls
(Un-)mute audio playback with the respecting multimedia key:
#+begin_src conf-space
  Key XF86AudioMute A A Exec exec pactl set-sink-mute \
      $(pactl get-default-sink) toggle
#+end_src

Raise and lower playback volume with the respecting multimedia keys:
#+begin_src conf-space
  Key XF86AudioLowerVolume A A Exec exec pactl set-sink-volume \
      $(pactl get-default-sink) -10%
  Key XF86AudioRaiseVolume A A Exec exec pactl set-sink-volume \
      $(pactl get-default-sink) +10%
#+end_src

(Un-)mute the microphone with the respecting multimedia key:
#+begin_src conf-space
  Key XF86AudioMicMute A A Exec exec pactl set-source-mute \
      $(pactl get-default-source) toggle
#+end_src

** Page navigation

Page navigation is done with the Numpad arrow keys or /H/, /J/, /K/ and /L/ while pressing /Super_L/:
#+begin_src conf-space
  Key J	     A 4 GotoPage  0p  1p
  Key KP_Down  A 4 GotoPage  0p  1p
  Key H	     A 4 GotoPage -1p  0p
  Key KP_Left  A 4 GotoPage -1p  0p
  Key L	     A 4 GotoPage  1p  0p
  Key KP_Right A 4 GotoPage  1p  0p
  Key K        A 4 GotoPage  0p -1p
  Key KP_Up    A 4 GotoPage  0p -1p
#+end_src

** Window control
Opens the [[* Menu for window operations][menu for window operations]] on the current window with /Super_L+O/:
#+begin_src conf-space
  Key O A 4 Menu MenuWindowOps
#+end_src

Opens the [[* Menu for sending windows to pages][menu for sending windows to pages]] on the current window with /Super_L+P/:
#+begin_src conf-space
  Key P A 4 Menu MenuWindowOps
#+end_src

Move the current window with /Super_L+M/:
#+begin_src conf-space
  Key M A 4 Move
#+end_src

Move the current window animated in a give direction with /Super_L+Shift+<Arrow-Key>/ until it hits another window or a screen boundary:
#+begin_src conf-space
  Key Up A 4S AnimatedMove shuffle Up
  Key Down A 4S AnimatedMove shuffle Down
  Key Left A 4S AnimatedMove shuffle Left
  Key Right A 4S AnimatedMove shuffle Right
#+end_src

Resize the current window with /Super_L+G/:
#+begin_src conf-space
  Key G A 4 Resize
#+end_src

Iconifies or deiconifies the current window with /Super_L+Down/:
#+begin_src conf-space
  Key Down A 4 Iconify
#+end_src

Maximizes or unmaximizes the current window with /Super_L+Up/:
#+begin_src conf-space
  Key Up A 4 Maximize
#+end_src

Raise the current window in its layer with /Super_L+R/
#+begin_src conf-space
  Key R A 4 Raise
#+end_src

Stick or unstick the current window with /Super_L+G/:
#+begin_src conf-space
  Key S A 4 Stick
#+end_src



** Deactivate M-Tab for mc
Some programms, like Midnight Commander use the combination /M-Tab/. Passing synthetic events to ~xterm~ like it is described on the [[https://www.fvwm.org/Man/fvwm3commands/#_mouse_key_bindings][FVWM3 man page]] leads to further problems and is therefore not the ideal way.

Alternatively the combination /M-Tab/ is deactivated and remapped to /Super_L-Tab/. Furthermore the: 
#+begin_src conf-space
  Key Tab A M -
  Key Tab A 4 WindowList Root c c NoGeometry, SelectOnRelease Super_L
#+end_src

* Mouse bindings
Add buttons to window title for (un-)maximize and (de-)iconify windows:
#+begin_src conf-space
  Mouse 1 1 A Menu MenuWindowOps Delete
  Mouse 1 2 A Maximize
  Mouse 1 4 A Iconify
#+end_src

Deiconify iconified windows with a mouse click:
#+begin_src conf-space
  Mouse 1 I A Iconify False
#+end_src

* Menus

** Root menu
Definition of the root menu:
#+begin_src conf-space
  DestroyMenu MenuFvwmRoot
  AddToMenu   MenuFvwmRoot "Fvwm" Title
  + "$[gt.XDG &Menu]%icons/apps.png%"	Popup XDGMenu
  + "&Terminal%icons/terminal.png%"	Exec exec x-terminal-emulator
  + ""					Nop
  + "Fvwm&Console%icons/terminal.png%"	Module FvwmConsole -terminal \
    x-terminal-emulator
  + "$[gt.Cop&y Config]%icons/conf.png%"	FvwmScript \
    FvwmScript-ConfirmCopyConfig
  + ""					Nop
  + "&Activate DP-1%icons/run_arrow.png%" ActivateMonitor DP-1
  + "&DeActivate DP-1"			DeActivateMonitor DP-1
  + ""					Nop
  + "$[gt.Re&fresh]%icons/refresh.png%"	Refresh
  + "$[gt.&Restart]%icons/restart.png%"	Restart

  + "$[gt.&Quit]%icons/quit.png%"	Module FvwmScript \
    FvwmScript-ConfirmQuit
  + "$[gt.&Hibernate]"			Exec exec systemctl hibernate
#+end_src

*** /freedesktop.org/ menu
Generate the /freedesktop.org/ menu with mini icons, which is used in the root menu:
#+begin_src conf-space
  PipeRead "fvwm3-menu-desktop -e --enable-mini-icons"
#+end_src

** Menu for window operations
Adding a menu with several window operations:
#+begin_src conf-space
  DestroyMenu MenuWindowOps
  AddToMenu   MenuWindowOps
   + "$[gt.&Identify]%icons/info.png%"		 Module FvwmIdent
   + ""						 Nop
   + "$[gt.&Move]%icons/win/move.png%"		 Move
   + "$[gt.Send To &Page]%icons/win/sendto.png%"	 Popup MenuSendToPage
   + ""						 Nop
   + "$[gt.Re&size]%icons/win/resize.png%"	 Resize
   + "$[gt.(De)Iconify]%icons/win/iconify.png%"	 Iconify
   + "$[gt.(Un)Maximize]%icons/win/max.png%"	 Maximize
   + ""						 Nop
   + "$[gt.&Raise]%icons/win/raise.png%"		 Raise
   + "$[gt.&Lower]%icons/win/lower.png%"		 Lower
   + ""						 Nop
   + "$[gt.Stays On &Top]%icons/win/top.png%"	 Pick (CirculateHit) Layer 0 6
   + "$[gt.Stays &Put]%icons/win/stays.png%"	 Pick (CirculateHit) Layer 0 4
   + "$[gt.Stays On &Bottom]%icons/win/bottom.png%" Pick (CirculateHit) Layer 0 2
   + ""						 Nop
   + "$[gt.(Un)&Sticky]%icons/win/sticky.png%"	 Stick
   + "$[gt.(Un)S&hade]%icons/win/shade.png%"	 WindowShade
   + "$[gt.Re&fresh Window]icons/refresh.png%"	 RefreshWindow
   + ""						 Nop
   + "$[gt.&Close]%icons/win/close.png%"		 Close
   + "$[gt.&Delete]%icons/win/done.png%"		 Delete
   + "$[gt.&Destroy]%icons/win/destroy.png%"	 Destroy
#+end_src

*** Menu for sending windows to pages
The window operation menu above uses a submenu for sending windows to a specific page:
#+begin_src conf-space
  DestroyMenu MenuSendToPage
  AddToMenu   MenuSendToPage
   + "$[gt.Page] &1 (0,0)" MoveToPage 0 0
   + "$[gt.Page] &2 (1,0)" MoveToPage 1 0
   + "$[gt.Page] &3 (2,0)" MoveToPage 2 0
   + "$[gt.Page] &4 (0,1)" MoveToPage 0 1
   + "$[gt.Page] &5 (1,1)" MoveToPage 1 1
   + "$[gt.Page] &6 (2,1)" MoveToPage 2 1
   + "$[gt.Page] &7 (0,2)" MoveToPage 0 2
   + "$[gt.Page] &8 (1,2)" MoveToPage 1 2
   + "$[gt.Page] &9 (2,2)" MoveToPage 2 2
#+end_src

** Focus policy
Windows should keep the focus until the mouse pointer hits another window and not the root window:
#+begin_src conf-space
  Style * SloppyFocus
#+end_src

*** JDownloader
/JDownloader/ sets the WM hint property ~input=false~, but does not take the focus, if it is selected via /WindowList/ from another page. To fix this, /JDownloader/ windows are given the lenient focus style:
#+begin_src conf-space
  Style JDownloader* FPLenient
#+end_src

* FvwmPager
1. Putting it on the top right corner
2. Do not show Desktop labels
3. Show mini icons of windows
4. Balloins are shown for un-iconified pager
5. Do not show windows using the style /WindowListSkip/

#+begin_src conf-space
  Style FvwmPager !Title, !Borders, !Handles, Sticky, WindowListSkip, NeverFocus

  DestroyModuleConfig FvwmPager:*
  ,*FvwmPager: Geometry -0+0
  ,*FvwmPager: Font None
  ,*FvwmPager: MiniIcons
  ,*FvwmPager: Balloons Pager
  ,*FvwmPager: UseSkipList
#+end_src

